# Generated by Django 6.0.7 on 2026-10-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
